
name: NPM Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dinamodigitale'
      - run: npm ci
      - run: npm run prepublish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DINAMO_GITHUB_TOKEN }}
